name = "mj-chatbot-backend"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
ENVIRONMENT = "development"

# KV namespace for rate limiting
[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "e872ef11e46c4f91ba2de157bdf48287"
